from tkinter import *
window = Tk()
window.title("Find the smallest number")
window.geometry("500x350+30+120")
def findSmallest():
    L = []
    L.append(eval(conOfent2.get()))
    L.append(eval(conOfent3.get()))
    L.append(eval(conOfent4.get()))
    conOfSmallest.set(min(L))

lbl1 = Label(window,text = "Enter the First number:")
lbl1.grid(row=2, column = 1,sticky=W)
conOfent2 = StringVar()
ent1 = Entry(window,bd=3,textvariable=conOfent2)
ent1.grid(row=2, column = 2)
lbl2 = Label(window,text = "Enter the Second number:")
lbl2.grid(row=3, column=1)
conOfent3=StringVar()
ent2 = Entry(window,bd=3,textvariable=conOfent3)
ent2.grid(row=3,column=2)
lbl3 = Label(window,text="Enter the Third number:")
lbl3.grid(row=4,column =1, sticky=W)
conOfent4 = StringVar()
ent3 = Entry(window,bd=3,textvariable=conOfent4)
ent3.grid(row=4, column=2)
btn1 = Button(window,text = "Find the Smallest number",command=findSmallest)
btn1.grid(row=6, column = 2)
lbl4 = Label(window,text="The smallest number:")
lbl4.grid(row=5,column=1,sticky=W)
conOfSmallest = StringVar()
ent4 = Entry(window,bd=3,state="readonly",textvariable=conOfSmallest)
ent4.grid(row=5,column=2)

mainloop()